### ISSUE TITLE
Update to latest https://github.com/yandex-cloud/go-sdk to address vulnerability in github.com/dgrijalva/jwt-go v3.2.0

### ISSUE THREAD

**Issue by nywilken** [hashicorp/packer-plugin-yandex#29]
A vulnerability was reported on github.com/dgrijalva/jwt-go v3.2.0. The fix requires the latest release of the [go-sdk]( https://github.com/yandex-cloud/go-sdk/commit/f1445c045dc9b2a9e414fa98539e7b6c8d8a81e5)

**Comment by GennadySpb** [comment]
Closed in #30 ?

**Comment by nywilken** [comment]
> Closed in #30 ?

Thanks @GennadySpb - I failed to link the issue to the PR. Closing.
