### ISSUE TITLE
Add support for selecting instance vCPU performance levels

### ISSUE THREAD

**Issue by dmitry-j-mikhin** [hashicorp/packer-plugin-yandex#80]
#### Description

At the moment, it is not possible to configure the vCPU performance levels of the created instance - https://cloud.yandex.com/en/docs/compute/concepts/performance-levels

#### Use Case(s)

In most cases image creation task is more IO/network bound, so there is no reason to allocate 100% vCPU resources, so it is desirable to allow usage of low vCPU performance levels to optimize costs.

**Comment by GennadySpb** [comment]
> @GennadySpb thank you for PR #81

You're welcome 😀
