### ISSUE TITLE
Parameter skip_create_image returns error

### ISSUE THREAD

**Issue by yarmyl** [hashicorp/packer-plugin-yandex#96]
#### Overview of the Issue

![изображение](https://github.com/hashicorp/packer-plugin-yandex/assets/14326402/20a21b5a-83f0-4449-9a2c-6568bdd929f8)

#### Reproduction Steps

when build with parameter `skip_create_image = true `

### Plugin and Packer version

packer version 1.9.4
yandex plugin version 1.1.3

### Simplified Packer Buildfile
```
source "yandex" "build" {
  zone         = "ru-central1-a"
  folder_id    = var.folder_id
  subnet_id    = var.subnet_id
  token        = var.token

  use_ipv4_nat = true

  source_image_family    = "ubuntu-2204-lts"

  skip_create_image      = true

  platform_id  = "standard-v3"
  disk_type    = "network-ssd"

  ssh_username = "ubuntu"
}

build {
  sources = ["source.yandex.build"]

  provisioner "shell" {
    inline = [
      "echo test"
    ]
  }

}
```

### Operating system and Environment details

`hashicorp/packer:latest` container from dockerhub

### Log Fragments and crash.log files
```
==> yandex.build: Destroying boot disk...
    yandex.build: Disk has been deleted!
2023/11/30 12:56:48 [INFO] (telemetry) ending yandex.build
==> Wait completed after 2 minutes 57 seconds
2023/11/30 12:56:48 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2023/11/30 12:56:48 machine readable: yandex.build,error []string{"Failed to find 'image' in state. Bug?"}
==> Builds finished but no artifacts were created.
2023/11/30 12:56:48 [INFO] (telemetry) Finalizing.
Build 'yandex.build' errored after 2 minutes 57 seconds: Failed to find 'image' in state. Bug?

```

**Comment by atrutnev** [comment]
Looks like it is not fixed yet. I'm using the latest version of plugin and getting the same error:

`[Step 5/6] Installed plugin github.com/hashicorp/yandex v1.1.3 in "/root/.packer.d/plugins/github.com/hashicorp/yandex/packer-plugin-yandex_v1.1.3_x5.0_linux_amd64"
<...>
[19:23:46]	[Step 5/6] Build '<build_name>' errored after 5 minutes 54 seconds: Failed to find 'image' in state. Bug?
[19:23:46]	[Step 5/6] 
[19:23:46]	[Step 5/6] ==> Wait completed after 5 minutes 54 seconds
[19:23:46]	[Step 5/6] 
[19:23:46]	[Step 5/6] ==> Some builds didn't complete successfully and had errors:
[19:23:46]	[Step 5/6] --> <build_name>: Failed to find 'image' in state. Bug?
[19:23:46]	[Step 5/6] 
[19:23:46]	[Step 5/6] ==> Builds finished but no artifacts were created.
[19:23:47]	[Step 5/6] Process exited with code 1
[19:23:47]	[Step 5/6] Process exited with code 1 (Step: <step_name> (Command Line))`

Packer version is latest as well - 1.11.2
Perhaps you need to create a new release? As I can see the latest release was on 28 November 2023 but this change was committed on 8 January 2024.
